name: psgs-drug
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - rdkit
  - openbabel
  - pyyaml
  - tqdm
  - pip
  - pip:
      - useful-rdkit-utils
